### ISSUE TITLE
Remove font inlining option

### ISSUE THREAD

**Issue by Munter** [Munter/subfont#10]
Inlining fonts while serving both woff2 and woff makes little sense. Either disallow inlining fonts, always serve woff, or let the user chose which single format to prefer for inlining

**Comment by papandreou** [comment]
Did we eventually decide that it isn’t really worth it?

**Comment by Munter** [comment]
Personally I don't feel like font inlining is a good thing to do. But I don't have the numbers to back it up. It might actually have some benefits in the external css case. But then again, you might be overloading, since you'll always load the font despite it possibly not being used on the page

**Comment by papandreou** [comment]
Yeah, I agree. It seems like some very specific conditions need to be met for it to potentially be of help:

* Only one format is in play (or we inline woff2 and we're OK with punishing users that don't have woff2 support)
* It's combined with `subsetPerPage` (which we're getting rid of) or the site happens to use all font variants on all pages

**Comment by Munter** [comment]
When you put it like that it does indeed become weirdly specific. Let's get rid of it.

**Comment by papandreou** [comment]
Hmm, [woff2 support](https://caniuse.com/#feat=woff2) is 95.41% globally. We could maybe add some sort of check for whether a given font variant is used on all pages, and then just inline the subset woff2. This would work regardless of the `inlineCss` setting.

My tolerance for these weirdly specific things is higher when we don't put them behind a cli switch that users have a hard time understanding :)

**Comment by papandreou** [comment]
Fixed in 6.0.0 (where the switch goes away, but the optimization is automatically applied when the circumstances are right)
