### ISSUE TITLE
Remove Javascript preload polyfill

### ISSUE THREAD

**Issue by Munter** [Munter/subfont#101]
Once Firefox starts supporting `<link rel="preload">` we should drop the javascript polyfill for preloading. It's adding a lot of complexity to the code, and when Firefox gets support, there is such a little extra percentage of browsers supported that it makes little sense.

See https://caniuse.com/#feat=link-rel-preload

Mozilla says Firefox 78 is probably where preload gets full support

**Comment by Yankovsky** [comment]
Or maybe make it configurable like --no-fallback.

**Comment by Munter** [comment]
Replaced by #119
