### ISSUE TITLE
Nonoptimal unicode range generated

### ISSUE THREAD

**Issue by Yankovsky** [Munter/subfont#106]
Hey!
For text content `bcd` subfont generates unicode-range: `U+64, U+20, U+62-63`. It could be shortened to `U+20, U+62-64`.

Example:
```
<html>
<head>
	<meta charset="UTF-8">
	<style>
		* {
			font-family: 'Amita', cursive;
		}
	</style>
	<link href="https://fonts.googleapis.com/css2?family=Amita&display=swap" rel="stylesheet">
</head>
<body>bcd</body>
</html>
```

Result:
```
	<style>@font-face {
		font-display: swap;
		font-family: Amita__subset;
		font-stretch: normal;
		font-style: normal;
		font-weight: 400;
		src: url(/subfont/Amita-400-dd21df1df2.woff2) format("woff2");
		unicode-range: U+64, U+20, U+62-63
	}</style>
```

**Comment by papandreou** [comment]
Nice catch! This should be a "good first issue" if you'd like to take a stab at it 🤗

**Comment by papandreou** [comment]
Sorry, couldn't resist taking a peek, and it was painfully obvious: https://github.com/Munter/subfont/pull/107

**Comment by Yankovsky** [comment]
You didn't give me a chance! Well done!

**Comment by papandreou** [comment]
Sorry about that 😅 

Will try to contain myself next time.
