### ISSUE TITLE
Make resemblejs comparisons work on OSX

### ISSUE THREAD

**Issue by Munter** [Munter/subfont#112]
I'm getting a lot of failures while running the tests locally.

They all basically fail with the same problem:

```
mismatchPercentage: 0.03 // should equal 0
```

This is one of those things we've run into before with a difference in binaries built for Linux and OSX.

@papandreou I don't recall us ever actually finding a good solution for this one. Did you happen to stumble upon one since we tried it last?

**Comment by Munter** [comment]
Come to think of it, when it's about text rendering this might actually not be due to resemblejs, but rather the different text rendering implementations across operating systems

**Comment by Munter** [comment]
If we can't get OSX to run green tests, I might want to isolate these tests to only run on CI by default

**Comment by papandreou** [comment]
Urgh, yes. It’t probably the font rendering, but could you post one of the image diffs here?

We have a similar problem with a service at work, and ended up running the test suite for that inside a docker container, also locally. Probably overkill here.

I think we should just skip those tests on OSX, or maybe increase the accepted mismatch percentage.

**Comment by papandreou** [comment]
Or... If it’s one of the tests that compares a screenshot before and after applying subfont, maybe there is actually a bug that only affects OSX? Because then the reference image is also captured on your local machine?

**Comment by Munter** [comment]
I'll attempt an OSX test setup on Travis. Can't hurt

**Comment by Munter** [comment]
https://travis-ci.org/github/Munter/subfont/jobs/707386007 seems to recreate the osx problem

**Comment by papandreou** [comment]
![Screenshot from 2020-07-12 19-04-16](https://user-images.githubusercontent.com/373545/87252370-af9f7400-c472-11ea-8810-068b204e318c.png)

Seems like it's only the new "missing glyphs" and "unused variants" test cases added in #105 that fail on OSX :thinking:

IIRC Travis doesn't support archiving artifacts, so would you mind sharing some of the images?

**Comment by Munter** [comment]
![image](https://user-images.githubusercontent.com/331790/87256139-88f03600-c490-11ea-90bd-e2f367259720.png)

**Comment by Yankovsky** [comment]
Yeah, it is a common problem. We run our screenshot tests only in CI environment because they fail locally due to difference in font rendering.

**Comment by Yankovsky** [comment]
It could be solved (probably) by disabling anti aliasing https://developer.mozilla.org/en-US/docs/Web/CSS/font-smooth
Could also be because of different version of the same font.

**Comment by papandreou** [comment]
@Yankovsky, these tests make a screenshot of a test case before and after applying subfont, then compares them. So both are made on the machine running the test.

Since the other tests of this kind work fine on OSX, I suspect there's an actual bug in play here. Maybe there's a bug in `pyftsubset`, or we're passing some switches to it that causes it to strip some features that were needed for that exact font to render correctly.

**Comment by papandreou** [comment]
I tried playing around with the "unused variants" test case on my linux box, and I can see a subtle difference if I zoom to 400%:

![anim](https://user-images.githubusercontent.com/373545/87534589-86f7c400-c696-11ea-904c-ab0edd82ae8c.gif)

Tried a fiddling with the `pyftsubset` switches, but couldn't get it to make a difference.

**Comment by papandreou** [comment]
Same goes for the "missing glyphs" test case:

![anim2](https://user-images.githubusercontent.com/373545/87535629-1782d400-c698-11ea-8886-0ef7dabdb915.gif)

We should probably open an issue with fonttools.

**Comment by papandreou** [comment]
I don't see any obvious smoking gun, though. If I run the Input Sans Regular font through `ttx` before and after subsetting, the `t` glyph comes out exactly the same:

```xml
    <TTGlyph name="t" xMin="70" yMin="-9" xMax="609" yMax="800">
      <contour>
        <pt x="449" y="-9" on="1"/>
        <pt x="350" y="-9" on="0"/>
        <pt x="240" y="89" on="0"/>
        <pt x="240" y="190" on="1"/>
        <pt x="240" y="510" on="1"/>
        <pt x="70" y="510" on="1"/>
        <pt x="70" y="600" on="1"/>
        <pt x="240" y="600" on="1"/>
        <pt x="240" y="800" on="1"/>
        <pt x="340" y="800" on="1"/>
        <pt x="340" y="600" on="1"/>
        <pt x="600" y="600" on="1"/>
        <pt x="600" y="510" on="1"/>
        <pt x="340" y="510" on="1"/>
        <pt x="340" y="199" on="1"/>
        <pt x="340" y="141" on="0"/>
        <pt x="398" y="85" on="0"/>
        <pt x="455" y="85" on="1"/>
        <pt x="493" y="85" on="0"/>
        <pt x="559" y="96" on="0"/>
        <pt x="589" y="105" on="1"/>
        <pt x="609" y="14" on="1"/>
        <pt x="575" y="4" on="0"/>
        <pt x="498" y="-9" on="0"/>
      </contour>
      <instructions>
        <assembly>
          PUSHW[ ]	/* 3 values pushed */
          1 24 25
          SRP1[ ]	/* SetRefPoint1 */
          SRP2[ ]	/* SetRefPoint2 */
          IP[ ]	/* InterpolatePts */
          SVTCA[0]	/* SetFPVectorToAxis */
          PUSHW[ ]	/* 1 value pushed */
          0
          RCVT[ ]	/* ReadCVT */
          IF[ ]	/* If */
            PUSHW[ ]	/* 1 value pushed */
            6
            MDAP[1]	/* MoveDirectAbsPt */
          ELSE[ ]	/* Else */
            PUSHW[ ]	/* 2 values pushed */
            6 15
            MIAP[0]	/* MoveIndirectAbsPt */
          EIF[ ]	/* EndIf */
          PUSHW[ ]	/* 1 value pushed */
          0
          RCVT[ ]	/* ReadCVT */
          IF[ ]	/* If */
            PUSHW[ ]	/* 1 value pushed */
            10
            MDAP[1]	/* MoveDirectAbsPt */
          ELSE[ ]	/* Else */
            PUSHW[ ]	/* 2 values pushed */
            10 15
            MIAP[0]	/* MoveIndirectAbsPt */
          EIF[ ]	/* EndIf */
          PUSHW[ ]	/* 1 value pushed */
          0
          RCVT[ ]	/* ReadCVT */
          IF[ ]	/* If */
            PUSHW[ ]	/* 1 value pushed */
            8
            MDAP[1]	/* MoveDirectAbsPt */
          ELSE[ ]	/* Else */
            PUSHW[ ]	/* 2 values pushed */
            8 17
            MIAP[0]	/* MoveIndirectAbsPt */
          EIF[ ]	/* EndIf */
          PUSHW[ ]	/* 1 value pushed */
          0
          RCVT[ ]	/* ReadCVT */
          IF[ ]	/* If */
            PUSHW[ ]	/* 1 value pushed */
            0
            MDAP[1]	/* MoveDirectAbsPt */
          ELSE[ ]	/* Else */
            PUSHW[ ]	/* 2 values pushed */
            0 9
            MIAP[0]	/* MoveIndirectAbsPt */
          EIF[ ]	/* EndIf */
          PUSHW[ ]	/* 1 value pushed */
          6
          SRP0[ ]	/* SetRefPoint0 */
          PUSHW[ ]	/* 2 values pushed */
          4 1
          MIRP[10100]	/* MoveIndirectRelPt */
          PUSHW[ ]	/* 1 value pushed */
          12
          MDRP[10000]	/* MoveDirectRelPt */
          PUSHW[ ]	/* 1 value pushed */
          0
          SRP0[ ]	/* SetRefPoint0 */
          PUSHW[ ]	/* 2 values pushed */
          17 1
          MIRP[10100]	/* MoveIndirectRelPt */
          IUP[0]	/* InterpolateUntPts */
          IUP[1]	/* InterpolateUntPts */
        </assembly>
      </instructions>
    </TTGlyph>
```

**Comment by papandreou** [comment]
Got https://github.com/Munter/subfont/pull/113 to work by switching these test cases over to a different font. I guess those copies of Input Mono and Output Sans might just have been of a questionable lineage, leading to ambiguities that caused `pyftsubset` and browsers to interpret them differently.

Let's pick it up again if we run into more cases.
