### ISSUE TITLE
memory access out of bounds

### ISSUE THREAD

**Issue by Lionad-Morotar** [Munter/subfont#145]
报错信息：
```bash
╰❯❯❯ npm run subfont

> fontmin-tool@1.0.0 subfont D:\@Github\blog-font-cdn
> subfont ./lab/7000.html -o ./tmp

Guessing --root from input files: file:///D:/@Github/blog-font-cdn/lab/
 ✔ 0.005 secs: logEvents
 ✔ 0.080 secs: loadAssets
 ✔ 0.019 secs: populate
 ✔ 0.001 secs: checkIncompatibleTypes
 ✔ 0.001 secs: applySourceMaps
 ✔ 0.002 secs: populate
 ✔ 0.001 secs: populate
 ⚠ WARN: lab\source\SourceHanSerifCN-SemiBold.otf - memory access out of bounds
         Including assets:
             lab\index.css

 ⚠ WARN: lab\source\SourceHanSerifCN-SemiBold.otf - memory access out of bounds
         Including assets:
             lab\index.css

 ✔ 0.019 secs: compressJavaScript
 ✔ 0.000 secs: writeAssetsToDisc
HTML/JS/CSS size increase: 168 B
Total savings: -168 B
Output written to file:///D:/@Github/blog-font-cdn/tmp/
```

错误来源：
![image](https://user-images.githubusercontent.com/26913795/118477092-e56f5200-b740-11eb-89f8-311aad5ca55c.png)

重现方式：
https://github.com/Lionad-Morotar/font-cdn

**Comment by papandreou** [comment]
@Lionad-Morotar, thanks for reporting this. I think it's a problem with one of the wasm-based tools we use for converting and subsetting fonts. I'll try to take a look soon.

**Comment by papandreou** [comment]
If you'd like to expedite the process, could you try to see if you can reproduce the problem with the involved font(s) with just https://github.com/papandreou/fontverter (https://github.com/fontello/wawoff2 / https://github.com/odemiral/woff2sfnt-sfnt2woff) or https://github.com/papandreou/subset-font in the picture?

**Comment by Lionad-Morotar** [comment]
看起来像是 WebAssembly 的错误：
![image](https://user-images.githubusercontent.com/26913795/118478557-9f1af280-b742-11eb-8af8-90d85aaafb70.png)

**Comment by papandreou** [comment]
Great, thanks! Then it seems like the problem is in https://github.com/harfbuzz/harfbuzzjs or our use of it.

@ebraminio, does this ring a bell? If not I can do some triaging tonight (CEST)

**Comment by ebraminio** [comment]
> does this ring a bell? If not I can do some triaging tonight (CEST)

We have in 'exports.memory.grow(400); // each page is 64kb in size' in https://github.com/papandreou/subset-font/blob/master/index.js#L10 and CJK font like that need much larger space, implementing dynamic memory growing in harfbuzzjs was possible but I tbh failed to figure it out yet having static defined / max memory size by user is a feature of its own, one solution also can be implementing the whole thing in emscripten which provides this by default (I preferred to not go with that control more the resulting .wasm file and skip emscripten wrapper which could have some other ways to do also now I see), guess for now increasing the memory (the referred line) probably would be best, the font is 10mb and maybe some 100mb would be enough for now (but there are also much bigger CJK fonts also, maybe you can extend dynamically given the font size also)

**Comment by papandreou** [comment]
@Lionad-Morotar, can you try to play with other values by locally changing that `exports.memory.grow(400)` line to see if that makes it work? Eg. to 2000?

**Comment by papandreou** [comment]
I can reproduce the error using https://github.com/Lionad-Morotar/font-cdn, except that my node crashes with `Bus error: 10` instead of reporting the error.

Changing 400 to 2000 fixes it for me, so I released subset-font 1.2.3 / subfont 6.0.2 what that change.

I played around with growing the WebAssembly heap dynamically based on the size of the original font, but then I ran into `Cannot perform %TypedArray%.prototype.set on a detached ArrayBuffer`. Seems like it'd require a new instantiation of `hb-subset.wasm` for each subsetting operation, which seems excessive.

Btw. @Lionad-Morotar, subfont no longer requires fonttools etc., so you can remove https://github.com/Lionad-Morotar/font-cdn/blob/0b0461f96fbf79389772a3bc359856cdd6d10b14/package.json#L7 🤗

Thanks for reporting the issue and @ebraminio for helping out!

**Comment by Lionad-Morotar** [comment]
It works ! Thanks !

**Comment by yisibl** [comment]
@ebraminio I submitted an issue https://github.com/harfbuzz/harfbuzzjs/issues/39
