### ISSUE TITLE
Does it support SPA?

### ISSUE THREAD

**Issue by AcrylicShrimp** [Munter/subfont#149]
Hello! First of all, thanks for this amazing work!

I'm going to use this to optimize my SPA application, and I'm wonder how do I use it.

1. How do I specify multiple paths while using a single `index.html`? Is it possible? I'm going to use the `--in-place` option on my `dist` directory.
2. Some of my pages emit ajax requests to get its content on-the-fly. Is there way to notify the subfont that the content is ready to serve via DOM event or something?

Thank you!

**Comment by papandreou** [comment]
> How do I specify multiple paths while using a single `index.html`? Is it possible? I'm going to use the `--in-place` option on my `dist` directory.

No, that's not supported presently, sorry.

> Some of my pages emit ajax requests to get its content on-the-fly. Is there way to notify the subfont that the content is ready to serve via DOM event or something?

Subfont does all its work at build time, so there's no runtime component to receive such a notification. Presently, only the content that's present in the static HTML (and on the initial load with the experimental `--dynamic` switch) will be traced out and included in the created subsets.

This means that subfont is definitely more well suited for static websites than SPAs. We've been thinking about some features that could still help with SPAs, though:

* Separate the font self-hosting and automatic preloading features from the subsetting feature. Then you could use only the first two and not bother with the subsetting (which is likely to break when your dynamic content gets added)
* Make it possible to declare a range of characters that must be included in the subsets (per `@font-face`) whether or not they're found in the static HTML. That could allow you to also use the subsetting feature.

**Comment by AcrylicShrimp** [comment]
@papandreou Thanks for your quick response!
