### ISSUE TITLE
Discover assets on CDNs?

### ISSUE THREAD

**Issue by papandreou** [Munter/subfont#15]
I wanted to play around with tracing https://opendyslexic.org/ but its CSS is on a CDN, so it doesn't get populated because of https://github.com/Munter/subfont/blob/28ce1e1c1e2fc9b6a0dd762cfe64b3014d58d156/bin/subfont#L134

I think we should refine the query a bit so those assets are discovered.

There's a bunch of other stuff with that site that breaks assetgraph, but I'll try to fix that :)

**Comment by Munter** [comment]
It might make sense to just take all `Css` assets we find. This should become easier with AssetGraph 4, where asset types are inferred from the relation up front I think.

I'd also like to do a different query for the clobbering mode for local files, where I really don't need to populate anything else than `Html` and `Css` assets to do the analysis and write back the updates

**Comment by papandreou** [comment]
I agree about following all relations to `Css` that we find, whether or not they're `crossorigin`. But `style-loader` and lazy-loaded stylesheets could also be referred to from JavaScript assets, so in the general case I think we need to follow most relations (obviously excluding `*Image` and `*Anchor`).

As for the local clobbering mode -- won't we need to "pull home" http-hosted CSS that contains `font-family` properties that need patching up? We can of course just define that it's out of scope, but for the eg. the opendyslexic.org experiment it would be nice if it just worked.
