### ISSUE TITLE
Upgrade AssetGraph to avoid vulnerability notice

### ISSUE THREAD

**Issue by thewilkybarkid** [Munter/subfont#152]
NPM is reporting https://npmjs.com/advisories/1753 as a result of `subfont > assetgraph > sw-precache > meow > trim-newlines`.

It seems that sw-precache was removed from AssetGraph a long time ago (https://github.com/assetgraph/assetgraph/commit/6b739f1b38c91dbeffa207c27886a9a2c226320d), but appears not to have been included in AssetGraph 6.

Could AssetGraph be updated to v7?

**Comment by papandreou** [comment]
Sure, fixed in 6.3.0.
