### ISSUE TITLE
How to use subfont to generate new woff2 file with only specific Glyphs? (cherry picking)

### ISSUE THREAD

**Issue by Jieiku** [Munter/subfont#163]
Is there a way to use subfont to grab only certain font glyphs, maybe by unicode value?

I am hoping to do it via command line on linux.

```
U+f100
U+f101
U+f104
U+f105
U+e801
U+e803
```

**Comment by Jieiku** [comment]
I just found something which uses this library: https://github.com/omacranger/fontawesome-subset/issues/16#issuecomment-1151744198

**Comment by papandreou** [comment]
Do you mean outside the context of a web page? Yeah, then one option is https://github.com/papandreou/subset-font, although it doesn't offer a CLI. It uses [harfbuzz](https://github.com/harfbuzz/harfbuzz) under the hood, which comes with a CLI tool called [`hb-subset`](https://harfbuzz.github.io/utilities.html) that you can use.

Alternatively you can use `pyftsubset` from https://github.com/fonttools/fonttools

**Comment by Jieiku** [comment]
I just implemented this: https://github.com/Jieiku/subfont

it seems to be getting the job done.

**Comment by Jieiku** [comment]
Now I just need to figure out how to combine or more font files into a single font file.

**Comment by Jieiku** [comment]
absolutely, will do it within the hour (not at my pc yet)

**Comment by Munter** [comment]
Thanks 😄
