### ISSUE TITLE
Escape character issue when inlineCSS is true - Font Awesome

### ISSUE THREAD

**Issue by tristancollins** [Munter/subfont#171]
When using Font Awesome (with Hugo, building via netlify) I get a working output with the default options in the netlify-plugin-subfont. However, when I make `inlineCss = true` I seem to get the same issue found in https://github.com/Munter/subfont/issues/128 and fixed in https://github.com/Munter/subfont/pull/132 . 

Failed to load resource - 404: `/subfont/font_awesome/_5_brands-400-b8f73f9e64.woff2`

There is no 'font_awesome' directory, as the escape character is being changed to a '/'. The file is called `font_awesome\_5_brands-400-b8f73f9e64.woff2`

subfont v6.12.4
netlify-plugin-subfont v6.0.0

**Comment by papandreou** [comment]
Can you share some more information so I can reproduce it?

**Comment by tristancollins** [comment]
I'll try and get a MWE together. It's in a private repo and building to a non-public (not yet public) site.

**Comment by papandreou** [comment]
I think I see what's wrong. Fixed in 6.12.5 / 7.1.1

**Comment by tristancollins** [comment]
Many thanks!
