### ISSUE TITLE
Subfont can't find fontTools

### ISSUE THREAD

**Issue by seaneking** [Munter/subfont#30]
Trying to subset local font files, but subfont keeps complaining that fonttools isn't installed, when it is. I'm not a Python user, so any pointers? Installed fonttools with the bundled macOS Python setup, does subfont rely on Python 3 or something?

Log:

```sh
sean@seans-macbook ~/Little Planet/Dev/littleplanetcreative.com ±master⚡ » subfont -i public/**/*.html
Guessing --root from input files: file:///Users/sean/Little%20Planet/Dev/littleplanetcreative.com/public
 ✔ 0.043 secs: logEvents
 ✔ 2.268 secs: loadAssets
 ✔ 2.956 secs: populate
 ✔ 0.169 secs: populate
/bin/sh: pyftsubset: command not found
 ℹ INFO: Local subsetting is not possible because fonttools are not installed. Falling back to only subsetting Google Fonts. Run `pip install fonttools brotli zopfli` to enable local font subsetting
 ✔ 4.094 secs: subsetFonts
 ✔ 0.037 secs: writeAssetsToDisc
Output written to file:///Users/sean/Little%20Planet/Dev/littleplanetcreative.com/public/
sean@seans-macbook ~/Little Planet/Dev/littleplanetcreative.com ±master⚡ » pip show fonttools
Name: fonttools
Version: 3.28.0
Summary: Tools to manipulate font files
Home-page: http://github.com/fonttools/fonttools
Author: Just van Rossum
Author-email: just@letterror.com
License: MIT
Location: /Users/sean/Library/Python/2.7/lib/python/site-packages
Requires:
Required-by:
```

**Comment by Munter** [comment]
That's actually a bit surprising. We shouldn't be depending on a specific python version. We check for the availability of fonttools subsetting by just trying to execute it with a `--help` argument and catch any error that might be thrown, which indicates that the executeable is not available: https://github.com/assetgraph/assetgraph/blob/master/lib/util/fonts/subsetLocalFont.js#L9-L15

The only thing I can think of that might be missing on your system is that `pyftsubset` is not available in your `$PATH`. Is that something you could check up on?

**Comment by seaneking** [comment]
Yep wasn't on `PATH` derp 🤦‍♂️
