### ISSUE TITLE
Download all original google fonts to self-host instead of delgating to googles css/font

### ISSUE THREAD

**Issue by Munter** [Munter/subfont#31]
The current implementation of subfont adds fallback font loading in case the subsets for one reason or another didn't contain all the needed glyphs. For google fonts we keep the original CSS include that the developer added in their source, but load it async.

We should switch away from using google fonts for fallbacks and instead self-host the fallbacks to take advantage of an already warmed up http2 connection.

- [ ] Retain the ability to use google fonts for subsetting
- [ ] Download google fonts in the desired formats. We already have https://github.com/Munter/subfont/blob/master/lib/downloadGoogleFonts.js but aren't using it
- [ ] Unify all steps beyond the point of creating the font subsets and fallback font references

**Comment by papandreou** [comment]
Hopefully it isn't too hard to make this not Google Web Fonts-specific? We use fast.fonts.net at work.

**Comment by Munter** [comment]
How's the licensing on fonts.com?

**Comment by papandreou** [comment]
Several of their packages allow self-hosting: https://www.fonts.com/web-fonts/self-hosting
