### ISSUE TITLE
Doesn't work with absolute resource path in link tags

### ISSUE THREAD

**Issue by huygn** [Munter/subfont#36]
Tools like `react-static` force absolute links (https://react-static.js.org/docs/config#siteroot) for sitemap.xml generation which causes links to look like this:

![screen shot 2018-07-18 at 6 38 40 pm](https://user-images.githubusercontent.com/10569203/42879170-e131e448-8ab9-11e8-91f7-e0954eab216b.jpg)

Is there any way to specifiy resource path where `subfont` will look into?

```
$ subfont ./dist/index.html -i --root ./dist --inline-css --no-recursive
 ✔ 0.025 secs: logEvents
 ✔ 0.174 secs: loadAssets
 ⚠ WARN: http://localhost:8000/main.css: connect ECONNREFUSED 127.0.0.1:8000
         Including assets:
             dist/index.html
             dist/index.html
...
```

**Comment by papandreou** [comment]
@huygn, thanks for getting in touch!

Try this:

```
subfont ./dist/index.html -i --root ./dist --inline-css --canonicalroot http://localhost:8080/
```

**Comment by huygn** [comment]
@papandreou Thanks it works greate 👍
