### ISSUE TITLE
Identical pages use different font files despite sharing identical subset

### ISSUE THREAD

**Issue by ksesong** [Munter/subfont#50]
When processing multiple identical pages, the resulting font files are different (with a different filename; the `md5` section (?) is identical, but there is an extra `-${i}` suffix to duplicates) despite sharing the same glyph subset.

I've set up a [test repository](https://github.com/ksesong/subfont-duplicate-issue), with two identical source pages, which should use the same font file after processing (`yarn build`), but `subfont` somehow yields two identical font files, each page referring to each of them.

**Comment by papandreou** [comment]
Thanks for the report, it was really easy to approach because of the repro case :heart:

Turned out this was a regression that got introduced in assetgraph/assetgraph#915. I've fixed it for the next release.

**Comment by papandreou** [comment]
Fix released in assetgraph 5.8.2. Since subfont has a dependency on assetgraph ^5.3.1, you should receive the fix if you run `yarn upgrade`.
