### ISSUE TITLE
Embedded iframes lead to errors

### ISSUE THREAD

**Issue by markmichon** [Munter/subfont#54]
I'm running into an issue where subfont will go into iframes, like embeds from codesandbox or glitch, and try to handle their typefaces. 

This often leads to a bunch of warnings, but eventually causes an error along the lines of:
```
Error: subsetFonts transform: Multiple @font-face with the same font-family/font-style/font-weight (maybe with different unicode-range?) is not supported yet
```
The underlying error, as can be seen in this [example repo](https://github.com/markmichon/subfont-error-demo) and seems to stem from trying to crawl the embeded iframes and running into conflicts or unsupported use cases when it tries to process their css.

**Comment by papandreou** [comment]
Thanks for the report, it was very easy to fix because of the enclosed test case :tada:

Fixed in 3.6.3.
