### ISSUE TITLE
Integration With Sapper

### ISSUE THREAD

**Issue by s0kil** [Munter/subfont#71]
I'm using subfont with [sapper](https://sapper.svelte.dev)
I'm getting errors such as:
`WARN: ENOENT: no such file or directory, open '__sapper__/export/contact/client/contact.e4e3f7ed.css'`

subfont is looking for a css file in the `__sapper__/export/contact/` directory when the link tag is `<link href="client/contact.e4e3f7ed.css" rel="stylesheet">`. It should look in the root folder such as `__sapper__/export/client`.

At the moment I end up rewriting the href tags for all pages in order for subfont to find the css files:
```js
const replaceInFiles = require("replace-in-files");

const options = {
  files: ["__sapper__/export/**/*.html"],
  from: /href=client/g,
  to: "href=/client"
};

replaceInFiles(options)
  .then(({ changedFiles, countOfMatchesByPaths, replaceInFilesOptions }) => {
    console.log("Modified files:", changedFiles);
    console.log("Count of matches by paths:", countOfMatchesByPaths);
    console.log("was called with:", replaceInFilesOptions);
  })
  .catch(error => {
    console.error("Error occurred:", error);
  });
```

Is there a way to tell subfont to start looking for assets in the root directory such as `__sapper__/export/` ?

**Comment by papandreou** [comment]
I can't fully picture what your project looks like. Is there a `<base href=...>` involved? Could you share a repo or zip file with what you're running subfont on?

**Comment by s0kil** [comment]
Yes there is an `base href=...>` involved:
```html
  <base href=/>
  <link href=global.css rel=stylesheet>
  <link href=client/main.850609924.css rel=stylesheet>
  <link href=client/index.ed5dc6bd.css rel=stylesheet>
``` 

subfont will look for `*.css` files in the folder the `*.html` file is located, and that results into an error such as `⚠ WARN: ENOENT: no such file or directory, open '__sapper__/export/about/global.css'` when instead subfont should look in the root directory `__sapper__/export/`.

Here is the repo https://github.com/s0kil/sapper-subfont:
- `npm run export`
- `npm run subfont`

**Comment by Munter** [comment]
I can recreate the issue with your repo. Looks to me like assetgraph doesn't pick up the `<base href="/">`. If that is true, a fix might take a while, since there can be many implications on how we deal with resolving urls

**Comment by papandreou** [comment]
Yeah, assetgraph doesn’t support `<base>`, so that’s definitely it.

**Comment by s0kil** [comment]
In order to simplify this problem, what about checking for assets in a priority, relative to `*.html` file, then root path, fallback to `ENOENT` ?

**Comment by papandreou** [comment]
Let’s get it fixed properly, it’s not really feasible for subfont to have a different url resolution strategy from assetgraph’s.

In the mean time you can remove the base tag and convert your relative paths to root-relative ones?

**Comment by s0kil** [comment]
I cannot control the output that Sapper generates, but after I modify it:
```js
const replaceInFiles = require("replace-in-files");

const options = {
  files: ["__sapper__/export/**/*.html"],
  from: /href=client/g,
  to: "href=/client"
};

replaceInFiles(options)
  .then(({ changedFiles, countOfMatchesByPaths, replaceInFilesOptions }) => {
    console.log("Modified files:", changedFiles);
    console.log("Count of matches by paths:", countOfMatchesByPaths);
    console.log("was called with:", replaceInFilesOptions);
  })
  .catch(error => {
    console.error("Error occurred:", error);
  });
```

**Comment by Munter** [comment]
I am actually a bit surprised that sapper promotes using `<base>` at all. It has quite a few surprising side-effects. I would have expected sapper to prepend its base in front of all generated URLs. But it does fall within the scope of Assetgraph to support the use case

**Comment by s0kil** [comment]
Is there anything else that `<base>` does besides specifying the base URL to use for all relative URLs?

**Comment by Munter** [comment]
See the notes section of https://webplatform.github.io/docs/html/elements/base/

Also I'm a bit unsure of Base will modify module import statements, which are supposed to be relative to the including files URL, or runtime imports, fetch and xhr. CSS also uses relative from origin file resolution. Also the concept of Base only applying to the things following it's declaration is confusing

**Comment by papandreou** [comment]
Tried implementing `<base href=...>` here: https://github.com/assetgraph/assetgraph/pull/1065

**Comment by Munter** [comment]
Subfont v4.0.5 has been released and should fix the problem with `<base>`.

@s0kil Even though subfont will not throw errors in your example case after the update I think you should switch your config from using subfonts output mode (`-o`) to using inline replacements (`-i`). I can see from my local runs that sapper does some things that our graph traversal doesn't quite pick up, so when subfont runs in output mode it is missing some files.
