### ISSUE TITLE
Don't use a subset if the result for some reason is larger than the original

### ISSUE THREAD

**Issue by Munter** [Munter/subfont#9]
Compare buffer of original font with buffer of subset result, and just throw away the subset if it is larger than original (and of the same format)

**Comment by Munter** [comment]
This case has never come up. Closing

**Comment by papandreou** [comment]
I still think we should keep it on the agenda. When a high percentage of characters are in use, it's wasteful to go through the exercise of adding the `@font-face` definitions for the subset variants and injecting the `__subset` into all `font-family` property values. In that case I think we should just self-host the font and call it a day.
